services:
  web:
    build: ./spring
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./spring:/srv:cached
    command: ["sh", "gradlew", "bootRun"]
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: