services:
  web:
    image: eclipse-temurin:17
    ports:
      - "5555:5555"
    tty: true
    volumes:
      - ./spring:/workspace:cached
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: